[book]
title = "The Business"
description = "A description of what I'm doing with my poker software"
authors = ["Clifford T. Matthews"]
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2018"

[output.html]
no-section-label = true
