[book]
title = "Craft Poker Co."
description = "A description of Craft Poker Co."
authors = ["Clifford T. Matthews"]
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2021"

[output.html]
no-section-label = true
