#! /bin/bash

# Ugh. I copied and pasted this from my Players' Manual.  It's ugly to duplicate code.

echo "This book should no longer be deployed." 1>&2
exit 1

set -o errexit
set -o pipefail

tmp_dir='/tmp/craft-poker-co-book'
github_io_dir="$(echo ~/ctm.github.io/docs/craft-poker-co)"

function add_and_push() {
    git add -A
    git commit -m '' --allow-empty-message
    git push
}

rm -rf "$tmp_dir"
git worktree add -f "$tmp_dir" gh-pages
mdbook build
rm -rf "$tmp_dir/*"
cp -rp book/* "$tmp_dir/"
( cd "$tmp_dir" && add_and_push )
( cd "$github_io_dir" && git pull && cd .. && add_and_push )
